/*package sk.adonikeoffice.epicmoderation.menu;

public enum Options {
	MESSAGE, // YOU CAN MESSAGE THE PLAYER
	TELEPORT, // YOU CAN TELEPORT TO THE PLAYER
	FREEZE, // YOU CAN FREEZE THE PLAYER
	KICK, // YOU CAN KICK THE PLAYER
	SPECTATE, // YOU CAN SPECTATE THE PLAYER IN FIRST PERSON MODE
	INVENTORY, // YOU CAN VIEW PLAYER INVENTORY
	ENDER_INVENTORY // YOU CAN VIEW PLAYER ENDER CHEST
}
*/